# Copyright 2022-2023 Chris Croome
#
# This file is part of the Webarchitects Element Ansible role.
#
# The Webarchitects Element Ansible role is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
#
# The Webarchitects Element Ansible role is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with the Webarchitects Element Ansible role. If not, see <https://www.gnu.org/licenses/>.
---
- name: Configure Element
  block:

    - name: Element config present
      ansible.builtin.template:
        src: config.json.j2
        dest: "/opt/element-{{ element_tag_proposed }}/config.{{ element_domain }}.json"
        backup: true
        mode: "0644"
        owner: root
        group: root
      register: element_configured

    - name: Copy files to the Element directory
      ansible.builtin.copy:
        src: "{{ element_path.src }}"
        dest: "/opt/element-{{ element_tag_proposed }}/{{ element_path.dest }}"
        mode: "{{ element_path.mode }}"
        owner: "{{ element_path.owner | default('root') }}"
        group: "{{ element_path.group | default('root') }}"
      loop: "{{ element_copy }}"
      loop_control:
        loop_var: element_path
      when:
        - element_copy is defined
        - element_copy != []

    - name: Element symlinked
      ansible.builtin.file:
        src: "/opt/element-{{ element_tag_proposed }}"
        dest: /var/www/element
        state: link
        follow: false
        mode: "0777"
        owner: root
        group: root
      register: element_symlinked

    - name: Provision a TLS cert if it doesn't exist or it doesn't contain the correct names
      block:

        - name: Include the acme.sh / Let's Encrypt role
          ansible.builtin.include_role:
            name: acmesh
            tasks_from: letsencrypt.yml
          vars:
            acmesh_common_name: "{{ element_domain }}"
            acmesh_subject_alt_names: "{{ element_domain_redirects }}"

        - name: Include the check tasks
          ansible.builtin.include_tasks: check.yml

      when: >-
        ( not element_cert.stat.exists | bool ) or
        ( not element_key.stat.exists | bool ) or
        ( element_cert_info.subject.commonName != element_matrix_domain ) or
        ( element_cert_info_sans != element_domain_redirects | sort )

    - name: Nginx config present
      ansible.builtin.template:
        src: nginx.conf.j2
        dest: "/etc/nginx/sites-available/{{ element_domain }}.conf"
        backup: true
        mode: "0644"
        owner: root
        group: root
      register: element_nginx_site_available
      when:
        - element_key.stat.exists | bool
        - element_cert.stat.exists | bool
      notify: Restart nginx

    - name: Stat Nginx config
      ansible.builtin.stat:
        path: "/etc/nginx/sites-available/{{ element_domain }}.conf"
      register: element_nginx_site_available_conf

    - name: Enable Nginx config
      block:

        - name: Nginx config symlinked
          ansible.builtin.file:
            state: link
            src: "/etc/nginx/sites-available/{{ element_domain }}.conf"
            dest: "/etc/nginx/sites-enabled/{{ element_domain }}.conf"
            follow: false
            mode: "0777"
            owner: root
            group: root
          notify: Restart nginx

        - name: Nginx configtest  # noqa yaml[comments] command-instead-of-module
          ansible.builtin.command: service nginx configtest
          check_mode: false
          changed_when: false
          register: element_nginx_configtest

      when: element_nginx_site_available_conf.stat.exists | bool

  tags:
    - element
    - element_config
...
